# Generated by Django 4.2.9 on 2024-02-08 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=20, verbose_name='Zipcode')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('bedrooms', models.IntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Bathrooms')),
                ('garage', models.IntegerField(default=0, verbose_name='Garage')),
                ('square_size', models.IntegerField(verbose_name='Square Feet')),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Lot Size')),
                ('images', models.ImageField(blank=True, upload_to='media/', verbose_name='Photos')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='List Date')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtorsmodel', verbose_name='Realtor')),
            ],
        ),
    ]
