# Generated by Django 4.2.9 on 2024-02-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_propertieslistingmodel_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_five',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_four',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_one',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_six',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_three',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
        migrations.AddField(
            model_name='propertieslistingmodel',
            name='photo_in_two',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Inside Photos'),
        ),
    ]
