# Generated by Django 4.2.9 on 2024-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Photo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Is MVP')),
                ('hire_date', models.DateTimeField(auto_now_add=True, verbose_name='Hire Date')),
            ],
        ),
    ]
