# Generated by Django 4.2.9 on 2024-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtorsmodel_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorsmodel',
            name='hire_date',
            field=models.DateTimeField(blank=True, verbose_name='Hire Date'),
        ),
    ]
